version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi_server_product_test
    external_links: 
      - postgres_product_test:postgres_product_test
    depends_on:
      - postgres
    networks:
      - server
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
  postgres:
    image: postgres:13.3
    container_name: postgres_product_test
    networks:
      - server
    env_file:
      - ./.env
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

networks:
  server: